# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ "master", "main", ** ]
  pull_request:
    branches: [ "master", "main", ** ]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure
      run: cmake -S . -B build -G "Visual Studio 17 2022"

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      run: ctest --test-dir build -C Release --output-on-failure
